"""Initial creation

Revision ID: aae47bdc13c9
Revises:
Create Date: 2025-04-08 00:04:12.423898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "aae47bdc13c9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the schema
    op.execute("CREATE SCHEMA IF NOT EXISTS user_example")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("modify_date", sa.DateTime(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True
        ),
        sa.Column(
            "phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="user_example",
    )
    op.create_table(
        "user_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("modify_date", sa.DateTime(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column(
            "address_line_1",
            sqlmodel.sql.sqltypes.AutoString(length=250),
            nullable=False,
        ),
        sa.Column(
            "address_line_2",
            sqlmodel.sql.sqltypes.AutoString(length=250),
            nullable=True,
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column(
            "state", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column(
            "postal_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_example.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
        schema="user_example",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_address", schema="user_example")
    op.drop_table("user", schema="user_example")
    # ### end Alembic commands ###

    # Drop the schema if you need to roll back
    op.execute("DROP SCHEMA IF EXISTS user_example")
