# Test your FastAPI endpoints

# Common endpoints

# healthcheck
GET {{api_host}}/framework/api/v1/common/healthcheck
Accept: application/json

###

# info
GET {{api_host}}/framework/api/v1/common/info
Accept: application/json

###

# User endpoints
GET {{api_host}}/framework/api/v1/user/healthcheck
Accept: application/json

###

POST {{api_host}}/framework/api/v1/user/create
Content-Type: application/json

{
  "username": "jdoe65",
  "description": "this is another test",
  "email": "user1@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "addresses": [
    {
      "type": 1,
      "address_line_1": "123 Main St",
      "address_line_2": null,
      "city": "New York",
      "state": "NY",
      "postal_code": "01234"
    }
  ],
  "phone_number": "555-555-1234",
  "status": "active"
}

###

PUT {{api_host}}/framework/api/v1/user/update
Content-Type: application/json

{
  "username": "jdoe65",
  "description": "this is another test",
  "email": "user1@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "addresses": [
    {
      "type": 3,
      "address_line_1": "PO Box 123",
      "address_line_2": null,
      "city": "New York",
      "state": "NY",
      "postal_code": "01234-0123"
    }
  ],
  "phone_number": "555-555-4321",
  "status": "active"
}

###

DELETE {{api_host}}/framework/api/v1/user/delete/jdoe65

###

GET {{api_host}}/framework/api/v1/user
Accept: application/json

###
GET {{api_host}}/framework/api/v1/user?search=jdoe
Accept: application/json

###

GET {{api_host}}/framework/api/v1/user/jdoe65
Accept: application/json
