# Test your FastAPI endpoints

# Common endpoints

# healthcheck
GET {{api_host}}/barrelapi/common/api/v1/healthcheck
Accept: application/json

###

# info
GET {{api_host}}/barrelapi/common/api/v1/info
Accept: application/json

###

# Workflow endpoints

POST {{api_host}}/barrelapi/workflows/api/v1/create-workflow
Content-Type: application/json

{
  "name": "test_workflow_v6",
  "description": "this is another test",
  "steps": [
    {
      "name": "step2",
      "type": "resolve",
      "index": 1,
      "inputs": {
        "mapping": "a"
      }
    }
  ],
  "inputs": [
    {
      "name": "dataset",
      "type": "Dataset"
    }
  ],
  "status": "draft"
}

###

PUT {{api_host}}/barrelapi/workflows/api/v1/update-workflow
Content-Type: application/json

{
  "name": "test_workflow_v6",
  "description": "this is update test",
  "steps": [
    {
      "name": "step1",
      "type": "resolve",
      "index": 0,
      "inputs": {
        "mapping1": "a",
        "mapping2": "b"
      }
    },
    {
      "name": "step2",
      "type": "renamer",
      "index": 1,
      "inputs": {
        "mapping1": "a",
        "mapping2": "b"
      }
    }
  ],
  "inputs": [
    {
      "name": "dataset",
      "type": "Dataset"
    }
  ],
  "status": "published"
}

### delete workflows

DELETE {{api_host}}/barrelapi/workflows/api/v1/delete-workflow/test_workflow_v6

### get all workflows

GET {{api_host}}/barrelapi/workflows/api/v1/get-workflows
Accept: application/json

### get all workflow by search
GET {{api_host}}/barrelapi/workflows/api/v1/get-workflows?search=test_workflow_v
Accept: application/json

### get workflow

GET {{api_host}}/barrelapi/workflows/api/v1/get-workflow/test_workflow_v3
Accept: application/json

### migrate list of pipeline id's

PATCH {{api_host}}/barrelapi/workflows/api/v1/migrate-workflow
Content-Type: application/json

{
    "workflows": [
        "spr:bz:pipeline::isc-jan:8",
        "spr:bz:pipeline::dnl-edi-exporteligd:2",
        "spr:bz:pipeline::fineos-demo-ml-infer:1",
        "spr:bz:pipeline::isc-step:2",
        "spr:bz:pipeline::ldex-bem:6",
        "spr:bz:pipeline::nb-workflow:12",
        "spr:bz:pipeline::new-business-v2-resolve:1",
        "spr:bz:pipeline::new-business-eoi:8",
        "spr:bz:pipeline::new-business-eoi-v2-resovle:2",
        "spr:bz:pipeline::new-business-eoi:9",
        "spr:bz:pipeline::dnlite-workflow:1",
        "spr:bz:pipeline::dnl-edi-exporteligd:6",
        "spr:bz:pipeline::enav-updated-workflow:39",
        "spr:bz:pipeline::member-maintenance-change-file-and-eoi:11"
    ]
}

### migrate workflow all

PATCH {{api_host}}/barrelapi/workflows/api/v1/migrate-workflow
Accept: application/json

{
    "workflows": null
}
